modLoader="javafml"
loaderVersion="[44,)"
license="All Rights Reserved unless stated otherwise. Distribution permission is given to FeedTheBeast and CurseForge for use in modpacks"
[[mods]]
modId="tramplestopper"
version="${file.jarVersion}"
displayName="Trample Stopper"
logoFile="logo.png"
authors="UnRealDinnerbone"
description='''
Stops Farmland Trampling
'''
[[dependencies.tramplestopper]]
modId="forge"
mandatory=true
versionRange="[44,)"
ordering="NONE"
side="BOTH"
[[dependencies.tramplestopper]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"
[[dependencies.tramplestopper]]
modId="trenzalore"
mandatory=true
versionRange="[${trenzalore_version},)"
ordering="NONE"
side="BOTH"