modLoader="javafml"
loaderVersion="[30,)"
license="All Rights Reserved unless stated otherwise. Distrubtion permssion is given to FeedTheBeast and CurseForge for use in modpacks"
[[mods]]
    modId="tramplestopper"
    version="${version}"
    displayName="Trample Stopper"
    description="Stops crop trampling"