name: Build & Release

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=2g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
  GIT_COMMIT: ${{ github.event.after }}
  GIT_PREVIOUS_COMMIT: ${{ github.event.before }}
  NANITE_DEPLOY: ${{ secrets.NANITE_DEPLOY  }}
  CURSE_DEPLOY: ${{ secrets.CURSE_DEPLOY }}
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 30 # Gets the last 30 commits so the changelog might work
      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Run Tests
        run: |
          chmod +x ./gradlew
          ./gradlew runGameTestServer --stacktrace --no-daemon
      - name: Build & release to curseforge
        run: |
          chmod +x ./gradlew
          ./gradlew build publish curseforge --stacktrace --no-daemon
